# Generated by Django 3.1.7 on 2021-03-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='User ID')),
                ('speech_datetime', models.DateTimeField(verbose_name='Call Date and Time Initiated')),
                ('speech_duration', models.DurationField(verbose_name='Call Duration')),
                ('language', models.CharField(max_length=50, verbose_name='Language')),
                ('accent', models.CharField(max_length=50, verbose_name='Accent')),
                ('stability', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Call Condifence')),
            ],
        ),
    ]
